/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tensorflow_bridge_Server */

#ifndef _Included_org_tensorflow_bridge_Server
#define _Included_org_tensorflow_bridge_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tensorflow_bridge_Server
 * Method:    Server_New_and_Start
 * Signature: (Lorg/tensorflow/distruntime/ServerDef;)V
 */
JNIEXPORT void JNICALL Java_org_tensorflow_bridge_Server_Server_1New_1and_1Start
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_tensorflow_bridge_Server
 * Method:    Server_New
 * Signature: (Lorg/tensorflow/distruntime/ServerDef;)Lorg/tensorflow/bridge/ServerInterface;
 */
JNIEXPORT jobject JNICALL Java_org_tensorflow_bridge_Server_Server_1New
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_tensorflow_bridge_Server
 * Method:    Server_Start
 * Signature: (Lorg/tensorflow/bridge/ServerInterface;)V
 */
JNIEXPORT void JNICALL Java_org_tensorflow_bridge_Server_Server_1Start
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_tensorflow_bridge_Server
 * Method:    Server_Stop
 * Signature: (Lorg/tensorflow/bridge/ServerInterface;)V
 */
JNIEXPORT void JNICALL Java_org_tensorflow_bridge_Server_Server_1Stop
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_tensorflow_bridge_Server
 * Method:    Server_Join
 * Signature: (Lorg/tensorflow/bridge/ServerInterface;)V
 */
JNIEXPORT void JNICALL Java_org_tensorflow_bridge_Server_Server_1Join
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
