/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.tensorflow.JNI;

public class server_lib {
  public static void PyServer_New(SWIGTYPE_p_ServerDef server_def, SWIGTYPE_p_TF_Status out_status) {
    server_libJNI.PyServer_New(SWIGTYPE_p_ServerDef.getCPtr(server_def), SWIGTYPE_p_TF_Status.getCPtr(out_status));
  }

  public static void PyServer_Start(SWIGTYPE_p_tensorflow__ServerInterface in_server, SWIGTYPE_p_TF_Status out_status) {
    server_libJNI.PyServer_Start(SWIGTYPE_p_tensorflow__ServerInterface.getCPtr(in_server), SWIGTYPE_p_TF_Status.getCPtr(out_status));
  }

  public static void PyServer_Stop(SWIGTYPE_p_tensorflow__ServerInterface in_server, SWIGTYPE_p_TF_Status out_status) {
    server_libJNI.PyServer_Stop(SWIGTYPE_p_tensorflow__ServerInterface.getCPtr(in_server), SWIGTYPE_p_TF_Status.getCPtr(out_status));
  }

  public static void PyServer_Join(SWIGTYPE_p_tensorflow__ServerInterface in_server, SWIGTYPE_p_TF_Status out_status) {
    server_libJNI.PyServer_Join(SWIGTYPE_p_tensorflow__ServerInterface.getCPtr(in_server), SWIGTYPE_p_TF_Status.getCPtr(out_status));
  }

  public static void setTensorflow(SWIGTYPE_p_namespace value) {
    server_libJNI.tensorflow_set(SWIGTYPE_p_namespace.getCPtr(value));
  }

  public static SWIGTYPE_p_namespace getTensorflow() {
    return new SWIGTYPE_p_namespace(server_libJNI.tensorflow_get(), true);
  }

}
